/*
 * Copyright 2024-2026 Bundesdruckerei GmbH
 * For the license see the accompanying file LICENSE.MD.
 */
package de.bdr.pidp.issuer.issuance.util;

import de.bdr.pidp.issuer.base.PidServerException;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.jspecify.annotations.NullMarked;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@NullMarked
@Slf4j
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class CountryCodeMapper {
    private static final Map<String, String> CODES;

    static {
        Map<String, String> map = new HashMap<>();
        map.put("ABW", "AW");
        map.put("AFG", "AF");
        map.put("AGO", "AO");
        map.put("AIA", "AI");
        map.put("ALA", "AX");
        map.put("ALB", "AL");
        map.put("AND", "AD");
        map.put("ARE", "AE");
        map.put("ARG", "AR");
        map.put("ARM", "AM");
        map.put("ASM", "AS");
        map.put("ATA", "AQ");
        map.put("ATF", "TF");
        map.put("ATG", "AG");
        map.put("AUS", "AU");
        map.put("AUT", "AT");
        map.put("AZE", "AZ");
        map.put("BDI", "BI");
        map.put("BEL", "BE");
        map.put("BEN", "BJ");
        map.put("BFA", "BF");
        map.put("BGD", "BD");
        map.put("BGR", "BG");
        map.put("BHR", "BH");
        map.put("BHS", "BS");
        map.put("BIH", "BA");
        map.put("BLM", "BL");
        map.put("BLR", "BY");
        map.put("BLZ", "BZ");
        map.put("BMU", "BM");
        map.put("BOL", "BO");
        map.put("BRA", "BR");
        map.put("BRB", "BB");
        map.put("BRN", "BN");
        map.put("BTN", "BT");
        map.put("BVT", "BV");
        map.put("BWA", "BW");
        map.put("CAF", "CF");
        map.put("CAN", "CA");
        map.put("CCK", "CC");
        map.put("CHE", "CH");
        map.put("CHL", "CL");
        map.put("CHN", "CN");
        map.put("CIV", "CI");
        map.put("CMR", "CM");
        map.put("COD", "CD");
        map.put("COG", "CG");
        map.put("COK", "CK");
        map.put("COL", "CO");
        map.put("COM", "KM");
        map.put("CPV", "CV");
        map.put("CRI", "CR");
        map.put("CUB", "CU");
        map.put("CUW", "CW");
        map.put("CXR", "CX");
        map.put("CYM", "KY");
        map.put("CYP", "CY");
        map.put("CZE", "CZ");
        map.put("DJI", "DJ");
        map.put("DMA", "DM");
        map.put("DNK", "DK");
        map.put("DOM", "DO");
        map.put("DZA", "DZ");
        map.put("ECU", "EC");
        map.put("EGY", "EG");
        map.put("ERI", "ER");
        map.put("ESH", "EH");
        map.put("ESP", "ES");
        map.put("EST", "EE");
        map.put("ETH", "ET");
        map.put("FIN", "FI");
        map.put("FJI", "FJ");
        map.put("FLK", "FK");
        map.put("FRA", "FR");
        map.put("FRO", "FO");
        map.put("FSM", "FM");
        map.put("GAB", "GA");
        map.put("GBR", "GB");
        map.put("GEO", "GE");
        map.put("GGY", "GG");
        map.put("GHA", "GH");
        map.put("GIB", "GI");
        map.put("GIN", "GN");
        map.put("GLP", "GP");
        map.put("GMB", "GM");
        map.put("GNB", "GW");
        map.put("GNQ", "GQ");
        map.put("GRC", "GR");
        map.put("GRD", "GD");
        map.put("GRL", "GL");
        map.put("GTM", "GT");
        map.put("GUF", "GF");
        map.put("GUM", "GU");
        map.put("GUY", "GY");
        map.put("HKG", "HK");
        map.put("HMD", "HM");
        map.put("HND", "HN");
        map.put("HRV", "HR");
        map.put("HTI", "HT");
        map.put("HUN", "HU");
        map.put("IDN", "ID");
        map.put("IND", "IN");
        map.put("IOT", "IO");
        map.put("IRL", "IE");
        map.put("IRN", "IR");
        map.put("IRQ", "IQ");
        map.put("ISL", "IS");
        map.put("ISR", "IL");
        map.put("ITA", "IT");
        map.put("JAM", "JM");
        map.put("JEY", "JE");
        map.put("JOR", "JO");
        map.put("JPN", "JP");
        map.put("KAZ", "KZ");
        map.put("KEN", "KE");
        map.put("KGZ", "KG");
        map.put("KHM", "KH");
        map.put("KIR", "KI");
        map.put("KNA", "KN");
        map.put("KOR", "KR");
        map.put("KWT", "KW");
        map.put("LAO", "LA");
        map.put("LBN", "LB");
        map.put("LBR", "LR");
        map.put("LBY", "LY");
        map.put("LCA", "LC");
        map.put("LIE", "LI");
        map.put("LKA", "LK");
        map.put("LSO", "LS");
        map.put("LTU", "LT");
        map.put("LUX", "LU");
        map.put("LVA", "LV");
        map.put("MAC", "MO");
        map.put("MAF", "MF");
        map.put("MAR", "MA");
        map.put("MCO", "MC");
        map.put("MDA", "MD");
        map.put("MDG", "MG");
        map.put("MDV", "MV");
        map.put("MEX", "MX");
        map.put("MHL", "MH");
        map.put("MKD", "MK");
        map.put("MLI", "ML");
        map.put("MLT", "MT");
        map.put("MMR", "MM");
        map.put("MNE", "ME");
        map.put("MNG", "MN");
        map.put("MNP", "MP");
        map.put("MOZ", "MZ");
        map.put("MRT", "MR");
        map.put("MTQ", "MQ");
        map.put("MUS", "MU");
        map.put("MWI", "MW");
        map.put("MYS", "MY");
        map.put("MYT", "YT");
        map.put("NAM", "NA");
        map.put("NCL", "NC");
        map.put("NER", "NE");
        map.put("NFK", "NF");
        map.put("NGA", "NG");
        map.put("NIC", "NI");
        map.put("NIU", "NU");
        map.put("NLD", "NL");
        map.put("NOR", "NO");
        map.put("NPL", "NP");
        map.put("NRU", "NR");
        map.put("NZL", "NZ");
        map.put("OMN", "OM");
        map.put("PAK", "PK");
        map.put("PAN", "PA");
        map.put("PCN", "PN");
        map.put("PER", "PE");
        map.put("PHL", "PH");
        map.put("PLW", "PW");
        map.put("PNG", "PG");
        map.put("POL", "PL");
        map.put("PRI", "PR");
        map.put("PRK", "KP");
        map.put("PRT", "PT");
        map.put("PRY", "PY");
        map.put("PSE", "PS");
        map.put("PYF", "PF");
        map.put("QAT", "QA");
        map.put("REU", "RE");
        map.put("ROU", "RO");
        map.put("RUS", "RU");
        map.put("RWA", "RW");
        map.put("SAU", "SA");
        map.put("SDN", "SD");
        map.put("SEN", "SN");
        map.put("SGP", "SG");
        map.put("SGS", "GS");
        map.put("SHN", "SH");
        map.put("SJM", "SJ");
        map.put("SLB", "SB");
        map.put("SLE", "SL");
        map.put("SLV", "SV");
        map.put("SMR", "SM");
        map.put("SOM", "SO");
        map.put("SPM", "PM");
        map.put("SRB", "RS");
        map.put("SSD", "SS");
        map.put("STP", "ST");
        map.put("SUR", "SR");
        map.put("SVK", "SK");
        map.put("SVN", "SI");
        map.put("SWE", "SE");
        map.put("SWZ", "SZ");
        map.put("SXM", "SX");
        map.put("SYC", "SC");
        map.put("SYR", "SY");
        map.put("TCA", "TC");
        map.put("TCD", "TD");
        map.put("TGO", "TG");
        map.put("THA", "TH");
        map.put("TJK", "TJ");
        map.put("TKL", "TK");
        map.put("TKM", "TM");
        map.put("TLS", "TL");
        map.put("TON", "TO");
        map.put("TTO", "TT");
        map.put("TUN", "TN");
        map.put("TUR", "TR");
        map.put("TUV", "TV");
        map.put("TWN", "TW");
        map.put("TZA", "TZ");
        map.put("UGA", "UG");
        map.put("UKR", "UA");
        map.put("UMI", "UM");
        map.put("URY", "UY");
        map.put("USA", "US");
        map.put("UZB", "UZ");
        map.put("VAT", "VA");
        map.put("VCT", "VC");
        map.put("VEN", "VE");
        map.put("VGB", "VG");
        map.put("VIR", "VI");
        map.put("VNM", "VN");
        map.put("VUT", "VU");
        map.put("WLF", "WF");
        map.put("WSM", "WS");
        map.put("XXA", "QS");
        map.put("XXB", "QU");
        map.put("XXC", "QU");
        map.put("XXK", "XK");
        map.put("XXX", "QU");
        map.put("YEM", "YE");
        map.put("ZAF", "ZA");
        map.put("ZMB", "ZM");
        map.put("ZWE", "ZW");
        map.put("D", "DE");

        CODES = Collections.unmodifiableMap(map);
    }

    public static String convertCountryCode(String countryCode) {
        if (StringUtils.isBlank(countryCode)) {
            log.error("Blank country code");
            throw new PidServerException("PID could not get issued due to an data issue. Please contact the support of Bundesdruckerei GmbH.");
        }

        String name = CODES.get(countryCode.toUpperCase());

        if (name == null) {
            log.error("Unknown country code");
            throw new PidServerException("PID could not get issued due to an data issue. Please contact the support of Bundesdruckerei GmbH.");
        }

        return name;
    }
}
