<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2024-2026 Bundesdruckerei GmbH
    For the license see the accompanying file LICENSE.MD.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
        <!-- lookup parent from repository -->
    </parent>
    <groupId>de.bdr.pidp</groupId>
    <artifactId>pidp-issuer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>PIDP-Issuer</name>
    <inceptionYear>2024</inceptionYear>
    <properties>
        <!-- language versions -->
        <java.version>25</java.version>
        <kotlin.version>2.4.10</kotlin.version>
        <kotlinx.version>1.9.0</kotlinx.version>

        <!-- dependency versions -->
        <spring-cloud.version>2025.1.2</spring-cloud.version>
        <mdoc-sdk-library.version>0.22.1</mdoc-sdk-library.version>
        <panstar-sdk.version>4.4.0</panstar-sdk.version>
        <google-zxing.version>3.5.4</google-zxing.version>
        <swagger-annotations.version>2.2.52</swagger-annotations.version>
        <spring-modulith.version>2.1.0</spring-modulith.version>
        <jmolecules.version>2025.0.2</jmolecules.version>
        <opentelemetry-logback-mdc-1.0.version>2.16.0-alpha</opentelemetry-logback-mdc-1.0.version>
        <oauth2-oidc-sdk.version>11.38.2</oauth2-oidc-sdk.version>
        <nimbus-jose-jwt.version>10.9.1</nimbus-jose-jwt.version>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <junit-pioneer.version>2.3.0</junit-pioneer.version>
        <jackson-core.version>3.2.1</jackson-core.version>
        <bouncycastle.version>1.85</bouncycastle.version>
        <velocity-engine-core.version>2.4.1</velocity-engine-core.version>
        <spring-web-test-client.version>6.0.1</spring-web-test-client.version>
        <postgresql.version>42.7.12</postgresql.version>
        <httpcore5.version>5.4.3</httpcore5.version>
        <log4j2.version>2.25.5</log4j2.version>
        <httpclient5.version>5.6.3</httpclient5.version>

        <jackson-bom.version>3.2.1</jackson-bom.version>
        <jackson-2-bom.version>2.22.1</jackson-2-bom.version>

        <!-- plugin version definitions -->
        <jruby.version>9.2.20.1</jruby.version>
        <xray-junit-extension.version>1.0.1</xray-junit-extension.version>
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>
        <pitest-maven.version>1.25.8</pitest-maven.version>
        <pitest-junit5-plugin.version>1.2.3</pitest-junit5-plugin.version>
        <license.maven.plugin.version>5.1.1</license.maven.plugin.version>
        <openapi.version>7.24.0</openapi.version>
        <asciidoctor-maven-plugin.version>3.2.0</asciidoctor-maven-plugin.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <java-uuid-generator.version>5.2.0</java-uuid-generator.version>

        <!-- other settings -->
        <test.groups>!restdocEid</test.groups>
        <sonar.sources>src/main/java,src/main/resources/templates,pom.xml</sonar.sources>
        <sonar.tests>src/test/java</sonar.tests>
        <sonar.junit.reportPaths>target/surefire-reports/</sonar.junit.reportPaths>
        <sonar.coverage.jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.projectName>pidp-issuer</sonar.projectName>
        <sonar.sarifReportPaths>roxctl_results.sarif</sonar.sarifReportPaths>
        <sonar-maven-plugin.version>5.7.0.6970</sonar-maven-plugin.version>
        <jmxPort>9001</jmxPort>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-core</artifactId>
            <version>${spring-modulith.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-restclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
            <version>3.5.16</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
            <version>2.0.13</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.vault</groupId>
            <artifactId>spring-vault-core</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jmolecules</groupId>
            <artifactId>jmolecules-hexagonal-architecture</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jmolecules</groupId>
            <artifactId>jmolecules-ddd</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-logback-mdc-1.0</artifactId>
            <version>${opentelemetry-logback-mdc-1.0.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europa.ec.eudi</groupId>
            <artifactId>eudi-lib-jvm-sdjwt-kt</artifactId>
            <version>0.17.3</version>
        </dependency>
        <dependency>
            <groupId>de.bundesdruckerei.mdoc.kotlin</groupId>
            <artifactId>mdoc-core-jvm</artifactId>
            <version>${mdoc-sdk-library.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/mdoc-core-jvm-0.22.1.jar</systemPath>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk15on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcutil-jdk15on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.i2p.crypto</groupId>
                    <artifactId>eddsa</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.upokecenter</groupId>
            <artifactId>cbor</artifactId>
            <version>4.5.6</version>
        </dependency>
        <dependency>
            <groupId>com.augustcellars.cose</groupId>
            <artifactId>cose-java</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>de.bundesdruckerei.mdoc.kotlin</groupId>
            <artifactId>blogg-jvm</artifactId>
            <version>${mdoc-sdk-library.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>${bouncycastle.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcutil-jdk18on</artifactId>
            <version>${bouncycastle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>${oauth2-oidc-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson-core.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.22</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>

        <!-- Kotlin part -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>${google-zxing.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>${google-zxing.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok-mapstruct-binding</artifactId>
            <version>0.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>${nimbus-jose-jwt.version}</version>
        </dependency>
        <dependency>
            <groupId>de.governikus.panstar.sdk</groupId>
            <artifactId>panstar-saml-sdk</artifactId>
            <version>${panstar-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.uuid</groupId>
            <artifactId>java-uuid-generator</artifactId>
            <version>${java-uuid-generator.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <!-- prevent double definition of JSON -->
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-test</artifactId>
            <version>${spring-modulith.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-webtestclient</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>spring-web-test-client</artifactId>
            <version>${spring-web-test-client.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <version>${junit-pioneer.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>app.getxray</groupId>
            <artifactId>xray-junit-extensions</artifactId>
            <version>${xray-junit-extension.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>1.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmolecules.integrations</groupId>
            <artifactId>jmolecules-archunit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents.core5</groupId>
            <artifactId>httpcore5-reactive</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>tools.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-cbor</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-restclient-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.json-unit</groupId>
            <artifactId>json-unit-assertj</artifactId>
            <version>6.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-test</artifactId>
            <version>1.17.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jmolecules</groupId>
                <artifactId>jmolecules-bom</artifactId>
                <version>${jmolecules.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.augustcellars.cose</groupId>
                <artifactId>cose-java</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>com.upokecenter</groupId>
                        <artifactId>cbor</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>de.governikus.panstar.sdk</groupId>
                <artifactId>panstar-utils</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${velocity-engine-core.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <sourceDirectory>${project.basedir}/src/main/java</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/java</testSourceDirectory>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${sonar-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <configuration>
                    <compilerPlugins>
                        <plugin>kotlinx-serialization</plugin>
                        <plugin>lombok</plugin>
                    </compilerPlugins>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-serialization</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-lombok</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>${lombok.version}</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${project.parent.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>
                            -Amapstruct.defaultComponentModel=spring
                        </arg>
                        <arg>
                            -Amapstruct.defaultInjectionStrategy=constructor
                        </arg>
                    </compilerArgs>
                </configuration>
                <executions>
                    <!-- Replacing default-compile as it is treated specially by Maven -->
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <!-- Replacing default-testCompile as it is treated specially by Maven -->
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>java-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>java-test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi.version}</version>
                <executions>
                    <execution>
                        <id>generate-info</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/eid.openapi.json</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>de.bdr.pidp.issuer.identification.in.api</apiPackage>
                            <modelPackage>de.bdr.pidp.issuer.identification.in.model</modelPackage>
                            <modelNamePrefix>Eid</modelNamePrefix>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <languageSpecificPrimitives>boolean</languageSpecificPrimitives>
                            <typeMappings>Boolean=boolean</typeMappings>
                            <configOptions>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                                <additionalApiTypeAnnotations>
                                    @Deprecated
                                </additionalApiTypeAnnotations>
                                <useSpringBoot3>true</useSpringBoot3>
                                <oas3>true</oas3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useSpringfox>false</useSpringfox>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <performBeanValidation>true</performBeanValidation>
                                <useDocumentationAnnotations>false</useDocumentationAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-mock-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/test/resources/mock.openapi.json</inputSpec>
                            <output>${project.build.directory}/generated-test-sources/openapi</output>
                            <generatorName>java</generatorName>
                            <apiPackage>de.bdr.pidp.issuer.eidauthmock.client.api</apiPackage>
                            <modelPackage>de.bdr.pidp.issuer.eidauthmock.client.model</modelPackage>
                            <modelNamePrefix>EidAuthMock</modelNamePrefix>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <languageSpecificPrimitives>boolean</languageSpecificPrimitives>
                            <typeMappings>Boolean=boolean</typeMappings>
                            <library>restclient</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <generateBuilders>true</generateBuilders>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                                <additionalApiTypeAnnotations>
                                    @Deprecated
                                </additionalApiTypeAnnotations>
                                <useSpringBoot3>true</useSpringBoot3>
                                <oas3>true</oas3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useSpringfox>false</useSpringfox>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <performBeanValidation>true</performBeanValidation>
                                <useDocumentationAnnotations>false</useDocumentationAnnotations>
                                <webclientBlockingOperations>true</webclientBlockingOperations>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jmxPort>${jmxPort}</jmxPort>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <configuration>
                    <append>true</append>
                    <dumpOnExit>true</dumpOnExit>
                    <fileSets>
                        <fileSet>
                            <directory>${project.build.directory}</directory>
                            <includes>
                                <include>*.exec</include>
                            </includes>
                        </fileSet>
                    </fileSets>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <groups>${test.groups}</groups>
                    <environmentVariables>
                        <CS_AUTH_KEYS>hsm/HSMauth.key</CS_AUTH_KEYS>
                    </environmentVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest-maven.version}</version>
                <configuration>
                    <timestampedReports>false</timestampedReports>
                    <excludedTestClasses>
                        <excludedTestClass>de.bdr.pidp.issuer.ArchitectureTests</excludedTestClass>
                    </excludedTestClasses>
                    <outputFormats>
                        <outputFormat>XML</outputFormat>
                        <outputForma>HTML</outputForma>
                    </outputFormats>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>${pitest-junit5-plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license.maven.plugin.version}</version>
                <configuration>
                    <licenseSets>
                        <licenseSet>
                            <inlineHeader>
                                Copyright $${license.git.copyrightYears} Bundesdruckerei GmbH
For the license see the accompanying file LICENSE.MD.
                            </inlineHeader>
                            <excludes>
                                <exclude>src/main/resources/metadata/*</exclude>
                                <exclude>src/main/resources/static/css/*.min.css*</exclude>
                                <exclude>src/main/resources/static/js/*</exclude>
                                <exclude>**/*.pem</exclude>
                                <exclude>**/*.crt</exclude>
                                <exclude>**/*.key</exclude>
                                <exclude>**/*.csr</exclude>
                                <exclude>.m2/**/*</exclude>
                                <exclude>**/*-log.txt</exclude>
                                <exclude>.run/*</exclude>
                                <exclude>**/*.tgz</exclude>
                                <exclude>**/*.lock</exclude>
                                <exclude>roxctl_results.sarif</exclude>
                                <exclude>src/main/resources/static/.well-known/security.txt</exclude>
                                <exclude>db/migrations/*.sql</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                    <strictCheck>true</strictCheck>
                    <aggregate>true</aggregate>
                    <mapping>
                        <feature>SCRIPT_STYLE</feature>
                        <Caddyfile>SCRIPT_STYLE</Caddyfile>
                        <Caddyfile.ci>SCRIPT_STYLE</Caddyfile.ci>
                        <Dockerfile-mig>SCRIPT_STYLE</Dockerfile-mig>
                        <http>SCRIPT_STYLE</http>
                        <bash>SCRIPT_STYLE</bash>
                        <txt>SCRIPT_STYLE</txt>
                    </mapping>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.mycila</groupId>
                        <artifactId>license-maven-plugin-git</artifactId>
                        <version>${license.maven.plugin.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>asciidoc-restdoceid</id>
            <activation>
                <file>
                    <exists>target/generated-snippets/health/curl-request.adoc</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <version>${asciidoctor-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>generate-docs</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <sourceDirectory>src/docs/asciidoc</sourceDirectory>
                                    <outputDirectory>${project.build.directory}/classes/static/docs</outputDirectory>
                                    <preserveDirectories>true</preserveDirectories>
                                    <doctype>book</doctype>
                                    <attributes>
                                        <webfonts>false</webfonts>
                                    </attributes>
                                    <logHandler>
                                        <outputToConsole>false</outputToConsole>
                                        <failIf>
                                            <severity>ERROR</severity>
                                        </failIf>
                                    </logHandler>
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>org.springframework.restdocs</groupId>
                                <artifactId>spring-restdocs-asciidoctor</artifactId>
                                <version>${spring-restdocs.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jacoco</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>jacoco</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <jvmArguments>${argLine}</jvmArguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
