#
# Copyright 2024-2026 Bundesdruckerei GmbH
# For the license see the accompanying file LICENSE.MD.
#

info.app.version=@project.version@

server.servlet.register-default-servlet=false
server.max-http-request-header-size=16000
server.tomcat.max-http-response-header-size=16000

spring.application.name=pid-issuer
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.password=<DB_PASSWORD>
spring.datasource.tomcat.max-active=1
spring.datasource.tomcat.max-idle=1
spring.datasource.url=<DB_URL>
spring.datasource.username=<DB_USERNAME>
spring.docker.compose.skip.in-tests=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
# cache docs/manual.html for 5 minutes
spring.web.resources.cache.cachecontrol.max-age=300
spring.web.resources.cache.cachecontrol.must-revalidate=true
# last modified is always set to 1980 which is why we have to disable it for caching to properly work
spring.web.resources.cache.use-last-modified=false

management.endpoint.health.access=unrestricted
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=unrestricted
management.endpoint.loggers.access=unrestricted
management.endpoints.access.default=none
management.endpoints.web.exposure.include=prometheus,health,loggers,authHousekeeping,identHousekeeping,issuanceHousekeeping
management.endpoints.web.path-mapping.authHousekeeping=housekeeping/authorization
management.endpoints.web.path-mapping.identHousekeeping=housekeeping/identification
management.endpoints.web.path-mapping.issuanceHousekeeping=housekeeping/issuance
management.endpoint.authHousekeeping.access=unrestricted
management.endpoint.identHousekeeping.access=unrestricted
management.endpoint.issuanceHousekeeping.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.server.port=9090
server.port=8080

pidi.base-url=http://localhost:8080
pidi.proof-time-tolerance=30s
pidi.proof-validity=2h
pidi.process-real-data=false
pidi.log-request-response=false
pidi.log-request-response.disabled=/health,/favicon.,/css/,/js/
pidi.log-request-response.without-details=/issuance-flow,/sdjwt,/msomdoc,/releases,/license,/privacy-terms,/docs/,/certificates/,/credentials/pid/,/.well-known/

pidi.authorization.base-url=${pidi.base-url}
pidi.authorization.process-real-data=${pidi.process-real-data}
pidi.authorization.challenge-enabled=true
pidi.authorization.request-uri-lifetime=60s
pidi.authorization.access-token-lifetime=60m
pidi.authorization.refresh-token-max-lifetime=730d
pidi.authorization.pop-nonce-lifetime=60s
pidi.authorization.authorization-code-lifetime=60s
pidi.authorization.proof-time-tolerance=${pidi.proof-time-tolerance}
pidi.authorization.proof-validity=${pidi.proof-validity}
pidi.authorization.session-expiration-time=60m
pidi.authorization.key-storage-types=iso_18045_high
pidi.authorization.user-authentication-types=iso_18045_high
pidi.authorization.at-sig-alias=<ALIAS>
pidi.authorization.rt-sig-alias=<ALIAS>
pidi.authorization.rt-sig-alias-hsm=<ALIAS>
pidi.authorization.rt-path=<RT_KEYSTORE>
pidi.authorization.rt-password=<RT_KEYSTORE_PASSWORD>

pidi.authorization.kms.transit-path=<PATH>

pidi.client.process-real-data=${pidi.process-real-data}
pidi.client.client-attestation-cert.<UUID_AS_IDENTIFIER>=<TRUST ANCHOR>
pidi.client.key-attestation-cert.<UUID_AS_IDENTIFIER>=<TRUST ANCHOR>

pidi.client.key-attestation-at-token-request-disabled-clients=<UUID>

pidi.issuance.base-url=${pidi.base-url}
pidi.issuance.process-real-data=${pidi.process-real-data}
pidi.issuance.signer-path=<SIGNER_KEYSTORE_PATH>
pidi.issuance.signer-password=<SIGNER_KEYSTORE_PASSWORD>
pidi.issuance.signer-alias=1
pidi.issuance.ca-cert-path=<PATH>
pidi.issuance.pid-sig-alias-hsm=<ALIAS>
pidi.issuance.lifetime=14d
pidi.issuance.max-validity=P5Y
pidi.issuance.batch-issuance-max-size=42
pidi.issuance.proof-time-tolerance=${pidi.proof-time-tolerance}
pidi.issuance.c-nonce-lifetime=60m
pidi.issuance.proof-validity=${pidi.proof-validity}
pidi.issuance.supported-configuration-ids=sd_jwt_v1,sd_jwt_v2,sd_jwt_v3_beta,mso_mdoc_v1,mso_mdoc_v2,mso_mdoc_v3_beta
pidi.issuance.creq-enc-ka-alias=<ALIAS>

pidi.issuance.kms.transit-path=<PATH>

pidi.identification.dump-pseudonym=false
pidi.identification.on-qa=false
pidi.identification.base-path=
pidi.identification.base-url=${pidi.base-url}
pidi.identification.frontend-url=<URL>
pidi.identification.initial-session-duration=1800s
pidi.identification.min-authenticated-session-duration=600s
pidi.identification.max-authenticated-session-duration=3600s
pidi.identification.max-identification-session-duration=${pidi.authorization.session-expiration-time}
pidi.identification.time-tolerance=${pidi.proof-time-tolerance}

pidi.identification.server.url=<URL>
pidi.identification.server.certificate-sig-paths=<PATHS>
pidi.identification.server.certificate-enc-path=<PATH>

pidi.identification.service-provider-name=http://localhost:8080

pidi.identification.xmlsig-keystore.path=<PATH>
pidi.identification.xmlsig-keystore.alias=<ALIAS>
pidi.identification.xmlsig-keystore.password=<PASSWORD>
pidi.identification.xmlenc-keystore.path=<PATH>
pidi.identification.xmlenc-keystore.alias=<ALIAS>
pidi.identification.xmlenc-keystore.password=<PASSWORD>

pidi.identification.create-seed-credential=true
pidi.identification.seed-path=<PATH>
pidi.identification.seed-password=<PASSWORD>
pidi.identification.seed-enc-alias=<ALIAS>
pidi.identification.seed-sig-alias=<ALIAS>
pidi.identification.seed-sig-alias-hsm=<ALIAS>

pidi.identification.kms.transit-path=<PATH>

pidi.statuslistservice.base-url=http://localhost:8086
pidi.statuslistservice.api-key=<API_KEY>
pidi.statuslistservice.pool-id=pidp

pidi.revocationservice.base-url=http://localhost:8082
pidi.revocationservice.api-key=<API_KEY>

pidi.metadata.signer-path=<PATH>
pidi.metadata.signer-password=<PASSWORD>
pidi.metadata.signer-alias=metadata-test
pidi.metadata.access-certificate-alias=access-certificate

pidi.doc.credential-configuration-ids=[{"credentialConfigurationId":"sd_jwt_v1","status":"DEPRECATED","activationDate":"2025-08-11","expirationDate":"2026-09-14"},{"credentialConfigurationId":"sd_jwt_v2","status":"ACTIVE","activationDate":"2026-08-19","expirationDate":null},{"credentialConfigurationId":"sd_jwt_v3_beta","status":"ACTIVE","activationDate":"2026-08-19","expirationDate":null},{"credentialConfigurationId":"mso_mdoc_v1","status":"DEPRECATED","activationDate":"2025-08-11","expirationDate":"2026-09-14"},{"credentialConfigurationId":"mso_mdoc_v2","status":"ACTIVE","activationDate":"2026-08-19","expirationDate":null},{"credentialConfigurationId":"mso_mdoc_v3_beta","status":"ACTIVE","activationDate":"2026-08-19","expirationDate":null}]

vault.uri=http://localhost:8200
vault.token=<TOKEN>

external-links.legal-notice=https://www.bundesdruckerei.de/en/legal-notice
external-links.privacy-terms=./privacy-terms
external-links.pid-signer-certificate=<PATH>
external-links.status-list-signer-certificate=<PATH>

hsm.enabled=false
