/*
 * Copyright 2024-2026 Bundesdruckerei GmbH
 * For the license see the accompanying file LICENSE.MD.
 */
package de.bdr.pidp.issuer.issuance.util;

import de.bdr.pidp.issuer.base.PidServerException;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.NullAndEmptySource;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class CountryCodeMapperTest {

    public static Stream<Arguments> validValues() {
        return Stream.of(
            arguments("ABW", "AW"),
            arguments("AFG", "AF"),
            arguments("AGO", "AO"),
            arguments("AIA", "AI"),
            arguments("ALA", "AX"),
            arguments("ALB", "AL"),
            arguments("AND", "AD"),
            arguments("ARE", "AE"),
            arguments("ARG", "AR"),
            arguments("ARM", "AM"),
            arguments("ASM", "AS"),
            arguments("ATA", "AQ"),
            arguments("ATF", "TF"),
            arguments("ATG", "AG"),
            arguments("AUS", "AU"),
            arguments("AUT", "AT"),
            arguments("AZE", "AZ"),
            arguments("BDI", "BI"),
            arguments("BEL", "BE"),
            arguments("BEN", "BJ"),
            arguments("BFA", "BF"),
            arguments("BGD", "BD"),
            arguments("BGR", "BG"),
            arguments("BHR", "BH"),
            arguments("BHS", "BS"),
            arguments("BIH", "BA"),
            arguments("BLM", "BL"),
            arguments("BLR", "BY"),
            arguments("BLZ", "BZ"),
            arguments("BMU", "BM"),
            arguments("BOL", "BO"),
            arguments("BRA", "BR"),
            arguments("BRB", "BB"),
            arguments("BRN", "BN"),
            arguments("BTN", "BT"),
            arguments("BVT", "BV"),
            arguments("BWA", "BW"),
            arguments("CAF", "CF"),
            arguments("CAN", "CA"),
            arguments("CCK", "CC"),
            arguments("CHE", "CH"),
            arguments("CHL", "CL"),
            arguments("CHN", "CN"),
            arguments("CIV", "CI"),
            arguments("CMR", "CM"),
            arguments("COD", "CD"),
            arguments("COG", "CG"),
            arguments("COK", "CK"),
            arguments("COL", "CO"),
            arguments("COM", "KM"),
            arguments("CPV", "CV"),
            arguments("CRI", "CR"),
            arguments("CUB", "CU"),
            arguments("CUW", "CW"),
            arguments("CXR", "CX"),
            arguments("CYM", "KY"),
            arguments("CYP", "CY"),
            arguments("CZE", "CZ"),
            arguments("DJI", "DJ"),
            arguments("DMA", "DM"),
            arguments("DNK", "DK"),
            arguments("DOM", "DO"),
            arguments("DZA", "DZ"),
            arguments("ECU", "EC"),
            arguments("EGY", "EG"),
            arguments("ERI", "ER"),
            arguments("ESH", "EH"),
            arguments("ESP", "ES"),
            arguments("EST", "EE"),
            arguments("ETH", "ET"),
            arguments("FIN", "FI"),
            arguments("FJI", "FJ"),
            arguments("FLK", "FK"),
            arguments("FRA", "FR"),
            arguments("FRO", "FO"),
            arguments("FSM", "FM"),
            arguments("GAB", "GA"),
            arguments("GBR", "GB"),
            arguments("GEO", "GE"),
            arguments("GGY", "GG"),
            arguments("GHA", "GH"),
            arguments("GIB", "GI"),
            arguments("GIN", "GN"),
            arguments("GLP", "GP"),
            arguments("GMB", "GM"),
            arguments("GNB", "GW"),
            arguments("GNQ", "GQ"),
            arguments("GRC", "GR"),
            arguments("GRD", "GD"),
            arguments("GRL", "GL"),
            arguments("GTM", "GT"),
            arguments("GUF", "GF"),
            arguments("GUM", "GU"),
            arguments("GUY", "GY"),
            arguments("HKG", "HK"),
            arguments("HMD", "HM"),
            arguments("HND", "HN"),
            arguments("HRV", "HR"),
            arguments("HTI", "HT"),
            arguments("HUN", "HU"),
            arguments("IDN", "ID"),
            arguments("IND", "IN"),
            arguments("IOT", "IO"),
            arguments("IRL", "IE"),
            arguments("IRN", "IR"),
            arguments("IRQ", "IQ"),
            arguments("ISL", "IS"),
            arguments("ISR", "IL"),
            arguments("ITA", "IT"),
            arguments("JAM", "JM"),
            arguments("JEY", "JE"),
            arguments("JOR", "JO"),
            arguments("JPN", "JP"),
            arguments("KAZ", "KZ"),
            arguments("KEN", "KE"),
            arguments("KGZ", "KG"),
            arguments("KHM", "KH"),
            arguments("KIR", "KI"),
            arguments("KNA", "KN"),
            arguments("KOR", "KR"),
            arguments("KWT", "KW"),
            arguments("LAO", "LA"),
            arguments("LBN", "LB"),
            arguments("LBR", "LR"),
            arguments("LBY", "LY"),
            arguments("LCA", "LC"),
            arguments("LIE", "LI"),
            arguments("LKA", "LK"),
            arguments("LSO", "LS"),
            arguments("LTU", "LT"),
            arguments("LUX", "LU"),
            arguments("LVA", "LV"),
            arguments("MAC", "MO"),
            arguments("MAF", "MF"),
            arguments("MAR", "MA"),
            arguments("MCO", "MC"),
            arguments("MDA", "MD"),
            arguments("MDG", "MG"),
            arguments("MDV", "MV"),
            arguments("MEX", "MX"),
            arguments("MHL", "MH"),
            arguments("MKD", "MK"),
            arguments("MLI", "ML"),
            arguments("MLT", "MT"),
            arguments("MMR", "MM"),
            arguments("MNE", "ME"),
            arguments("MNG", "MN"),
            arguments("MNP", "MP"),
            arguments("MOZ", "MZ"),
            arguments("MRT", "MR"),
            arguments("MTQ", "MQ"),
            arguments("MUS", "MU"),
            arguments("MWI", "MW"),
            arguments("MYS", "MY"),
            arguments("MYT", "YT"),
            arguments("NAM", "NA"),
            arguments("NCL", "NC"),
            arguments("NER", "NE"),
            arguments("NFK", "NF"),
            arguments("NGA", "NG"),
            arguments("NIC", "NI"),
            arguments("NIU", "NU"),
            arguments("NLD", "NL"),
            arguments("NOR", "NO"),
            arguments("NPL", "NP"),
            arguments("NRU", "NR"),
            arguments("NZL", "NZ"),
            arguments("OMN", "OM"),
            arguments("PAK", "PK"),
            arguments("PAN", "PA"),
            arguments("PCN", "PN"),
            arguments("PER", "PE"),
            arguments("PHL", "PH"),
            arguments("PLW", "PW"),
            arguments("PNG", "PG"),
            arguments("POL", "PL"),
            arguments("PRI", "PR"),
            arguments("PRK", "KP"),
            arguments("PRT", "PT"),
            arguments("PRY", "PY"),
            arguments("PSE", "PS"),
            arguments("PYF", "PF"),
            arguments("QAT", "QA"),
            arguments("REU", "RE"),
            arguments("ROU", "RO"),
            arguments("RUS", "RU"),
            arguments("RWA", "RW"),
            arguments("SAU", "SA"),
            arguments("SDN", "SD"),
            arguments("SEN", "SN"),
            arguments("SGP", "SG"),
            arguments("SGS", "GS"),
            arguments("SHN", "SH"),
            arguments("SJM", "SJ"),
            arguments("SLB", "SB"),
            arguments("SLE", "SL"),
            arguments("SLV", "SV"),
            arguments("SMR", "SM"),
            arguments("SOM", "SO"),
            arguments("SPM", "PM"),
            arguments("SRB", "RS"),
            arguments("SSD", "SS"),
            arguments("STP", "ST"),
            arguments("SUR", "SR"),
            arguments("SVK", "SK"),
            arguments("SVN", "SI"),
            arguments("SWE", "SE"),
            arguments("SWZ", "SZ"),
            arguments("SXM", "SX"),
            arguments("SYC", "SC"),
            arguments("SYR", "SY"),
            arguments("TCA", "TC"),
            arguments("TCD", "TD"),
            arguments("TGO", "TG"),
            arguments("THA", "TH"),
            arguments("TJK", "TJ"),
            arguments("TKL", "TK"),
            arguments("TKM", "TM"),
            arguments("TLS", "TL"),
            arguments("TON", "TO"),
            arguments("TTO", "TT"),
            arguments("TUN", "TN"),
            arguments("TUR", "TR"),
            arguments("TUV", "TV"),
            arguments("TWN", "TW"),
            arguments("TZA", "TZ"),
            arguments("UGA", "UG"),
            arguments("UKR", "UA"),
            arguments("UMI", "UM"),
            arguments("URY", "UY"),
            arguments("USA", "US"),
            arguments("UZB", "UZ"),
            arguments("VAT", "VA"),
            arguments("VCT", "VC"),
            arguments("VEN", "VE"),
            arguments("VGB", "VG"),
            arguments("VIR", "VI"),
            arguments("VNM", "VN"),
            arguments("VUT", "VU"),
            arguments("WLF", "WF"),
            arguments("WSM", "WS"),
            arguments("XXA", "QS"),
            arguments("XXB", "QU"),
            arguments("XXC", "QU"),
            arguments("XXK", "XK"),
            arguments("XXX", "QU"),
            arguments("YEM", "YE"),
            arguments("ZAF", "ZA"),
            arguments("ZMB", "ZM"),
            arguments("ZWE", "ZW"),
            arguments("D", "DE")
        );
    }

    @ParameterizedTest
    @MethodSource("validValues")
    void shouldValidCountryCodes(String source, String expected) {
        assertEquals(expected, CountryCodeMapper.convertCountryCode(source));
    }

    @ParameterizedTest
    @ValueSource(strings = {"_", "!-", "ZYX", "DEU", "DE", "AF", "123", "BQAQ", "AAA", "AA", "Z", "GBD", "GBN", "GBO", "GBS", "GBP", "KS", "RKS", "EU", "EUE"})
    @NullAndEmptySource
    void shouldInValidCountryCodes(String invalid) {
        assertThrows(PidServerException.class, () -> CountryCodeMapper.convertCountryCode(invalid));
    }
}
